-- 코드를 작성해주세요
SELECT
    COUNT(FISH_INFO.FISH_TYPE) AS FISH_COUNT,
    FISH_NAME
FROM
    FISH_INFO
INNER JOIN
    FISH_NAME_INFO
ON
    FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
GROUP BY
    FISH_NAME
ORDER BY
    COUNT(FISH_INFO.FISH_TYPE) DESC
