-- 코드를 입력하세요
WITH USERS AS (
    SELECT 
        *
    FROM 
        USER_INFO
    WHERE 
        YEAR(JOINED) = 2021
)

SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USERS.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT USERS.USER_ID) / (SELECT COUNT(*) FROM USERS), 1) AS RATIO
FROM 
    ONLINE_SALE
INNER JOIN 
    USERS 
ON
    USERS.USER_ID = ONLINE_SALE.USER_ID
GROUP BY 
    YEAR(SALES_DATE), 
    MONTH(SALES_DATE)
ORDER BY 
    YEAR,
    MONTH
