-- 코드를 입력하세요
SELECT
    RI.REST_ID,
    REST_NAME,
    FOOD_TYPE,
    FAVORITES,
    ADDRESS,
    ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM
    REST_INFO AS RI
INNER JOIN
    REST_REVIEW AS RR
ON
    RI.REST_ID = RR.REST_ID
WHERE
    ADDRESS LIKE "서울%"
GROUP BY
    RI.REST_ID
ORDER BY
    SCORE DESC,
    FAVORITES DESC
