-- 코드를 작성해주세요
SELECT 
    ITEM_INFO.ITEM_ID, 
    ITEM_INFO.ITEM_NAME, 
    ITEM_INFO.RARITY
FROM 
    ITEM_INFO
LEFT JOIN 
    ITEM_TREE ON ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
WHERE ITEM_INFO.ITEM_ID NOT IN (
    SELECT 
        PARENT_ITEM_ID
    FROM 
        ITEM_TREE
    WHERE 
        PARENT_ITEM_ID IS NOT NULL
)
ORDER BY 
    ITEM_INFO.ITEM_ID DESC;
