-- 코드를 작성해주세요
SELECT 
    II2.ITEM_ID, 
    II2.ITEM_NAME, 
    II2.RARITY
FROM 
    ITEM_INFO II1
INNER JOIN 
    ITEM_TREE IT 
ON 
    II1.ITEM_ID = IT.PARENT_ITEM_ID
INNER JOIN 
    ITEM_INFO II2 
ON 
    II2.ITEM_ID = IT.ITEM_ID
WHERE 
    II1.RARITY = 'RARE'
ORDER 
    BY II2.ITEM_ID DESC;
