-- 코드를 입력하세요
SELECT
    USER_ID,
    NICKNAME,
    CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS 전체주소,
    CONCAT( LEFT(TLNO, 3) , "-" , MID(TLNO,4,4) , "-", RIGHT(TLNO,4)) AS 전화번호
FROM
(
    SELECT
        *
    FROM
        USED_GOODS_BOARD
    GROUP BY
        WRITER_ID
    HAVING
        COUNT(*) >= 3
) AS UGB
INNER JOIN
    USED_GOODS_USER AS UGU
ON
    UGB.WRITER_ID = UGU.USER_ID
ORDER BY
    USER_ID DESC
