-- 코드를 입력하세요
SELECT
    BOOK.CATEGORY,
    SUM(BOOK_SALES.SALES) AS TOTAL_SALES
FROM
    BOOK
INNER JOIN
    BOOK_SALES
ON
    BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE
    BOOK_SALES.SALES_DATE >= '2022-01-01'
AND
    BOOK_SALES.SALES_DATE < '2022-02-01'
GROUP BY
    CATEGORY
ORDER BY
    CATEGORY ASC
