-- 코드를 입력하세요
SELECT
    CRCR.CAR_ID,
    CRCR.CAR_TYPE,
    ROUND(CRCR.DAILY_FEE * 30 * (100 - CRCDP.DISCOUNT_RATE) / 100, 0) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR AS CRCR
INNER JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP
ON
    CRCR.CAR_TYPE = CRCDP.CAR_TYPE
WHERE
    CRCR.CAR_ID NOT IN (
        SELECT 
            CAR_ID
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE 
            END_DATE >= '2022-11-01'
        AND
            START_DATE < '2022-12-01'
    )
AND
    (
        CRCR.CAR_TYPE = '세단'
        OR
        CRCR.CAR_TYPE = 'SUV'
    )
AND
    CRCDP.DURATION_TYPE = '30일 이상'
GROUP BY
    CRCR.CAR_ID
HAVING
    FEE BETWEEN 500000 AND 2000000
ORDER BY
    FEE DESC,
    CAR_TYPE ASC,
    CAR_ID DESC
